# Generated by Django 4.2.24 on 2025-09-12 02:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('char', '자모'), ('word', '단어'), ('sentence', '문장'), ('braille', '점자변환')], max_length=20)),
                ('source', models.CharField(choices=[('manual', '수동추가'), ('quiz_wrong', '퀴즈오답'), ('free_convert', '자유변환'), ('learning_queue', '학습큐')], default='manual', max_length=20)),
                ('content', models.JSONField(help_text='학습 내용 (JSON)')),
                ('ease_factor', models.FloatField(default=2.5)),
                ('interval', models.IntegerField(default=1)),
                ('repetitions', models.IntegerField(default=0)),
                ('next_due', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['next_due', 'created_at'],
                'indexes': [models.Index(fields=['next_due', 'type'], name='learning_re_next_du_7568aa_idx'), models.Index(fields=['type', 'source'], name='learning_re_type_d9db90_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReviewAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(choices=[(0, '틀림'), (1, '어려움'), (2, '보통'), (3, '쉬움'), (4, '완벽')])),
                ('response_time', models.FloatField(blank=True, help_text='응답 시간 (초)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning.reviewitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
